[package]
name = "boundbook"
version = "0.1.0"
edition = "2024"
authors = ["The Motherfucking Bearodactyl", "ef1500"]
readme = "README.md"
keywords = ["comics", "manga", "bbf", "cli"]
categories = ["multimedia", "encoding"]
description = "A Rust rewrite of the Bound Book format by ef1500"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
memmap2 = "0.9.9"
rayon = "1.11.0"
thiserror = "2.0.18"
twox-hash = "2.1.2"
