[package]
name = "boundbook"
version = "0.1.0"
edition = "2024"
authors = ["The Motherfucking Bearodactyl", "ef1500"]
readme = "README.md"
keywords = ["comics", "manga", "bbf", "cli"]
categories = ["multimedia", "encoding"]
description = "A Rust rewrite of the Bound Book format by ef1500"
license-file = "LICENSE"
homepage = "https://github.com/TheBearodactyl/boundbook"
repository = "https://github.com/TheBearodactyl/boundbook"

[dependencies]
arboard = "3.6.1"
clap = { version = "4.5.56", features = ["derive"] }
color-eyre = "0.6.5"
crossterm = "0.29.0"
icy_sixel = "0.5.0"
image = "0.25.9"
indicatif = { version = "0.18.3", features = ["improved_unicode"] }
memmap2 = "0.9.9"
rayon = "1.11.0"
thiserror = "2.0.18"
twox-hash = "2.1.2"
zip = "7.2.0"
